apiVers: v1 
modelName: nlp-v1 # this should match the model filename within model folder
modelType: ModelType1 
ip: "127.0.0.1"
port: 5000
lookupTable: 
  species:
    - "guinea pig"
    - "cat"
    - "bird"
    - "dog"
  allergens:
    - "spinach"
    - "beef"
    - "chicken"
    - "pork"
    - "rice"
    - "banana"
    - "apple"
    - "pea"
    - "potato"
    - "apricots"
    - "fish"
    - "carrot"
    - "corn"
    - "wheat"
    - "soy"
    - "blueberry"
    - "pumpkin"
    - "cranberry"
    - "lamb"
    - "barley"
    - "strawberry"
    - "oat"
    - "egg"
    - "fruit"
    - "milk"
    - "cheese"
    - "lettuce"
    - "turkey"
    - "orange"
    - "rabbit"
    - "duck"
    - "berry"
    - "tomato"
    - "almond"
    - "broccoli"
  positive: # Words that describe the relationship between animal and food (not allergic)
    - "love"
    - "like"
    - "enjoy"
    - "great"
    - "awesome"
    - "delicious"
  negative: # Words that describe the relationhip between animal and food (allergic)
    - "hate"
    - "dislike"
    - "awful"
    - "terrible"
    - "bad"
    - "not"
    - "sensitive"
    - "allergic"
    - "allergies"

